name: junmintiaowo
on:
  workflow_dispatch:
  schedule:
    - cron: '51 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: junmintiaowo
        env:
          h4864: ${{ secrets.h4864 }}
        run: |
          echo $h4864 | jq -r .eleh175 | /bin/bash
          echo $tr2615 | jq -r .aj091 | /bin/bash
          echo $h00 | jq -r .xjf555 | /bin/bash
          echo $v0645 | jq -r .dmon30962 | /bin/bash
          echo $hpeag564 | jq -r .zyndr153 | /bin/bash
          echo $chvkv59655 | jq -r .jamma6 | /bin/bash
          echo $te03 | jq -r .nilgn90 | /bin/bash
          echo $pab68 | jq -r .ca9 | /bin/bash
          echo $c84 | jq -r .b85 | /bin/bash
          echo $mwqs56000 | jq -r .xrpgd1263 | /bin/bash
          echo $kqfpz27 | jq -r .j72434 | /bin/bash
          echo $j6044 | jq -r .ofnpp6466 | /bin/bash
          echo $rgf097 | jq -r .bfr55 | /bin/bash
          echo $zshbt230 | jq -r .mrxw4 | /bin/bash
          echo $tzp199 | jq -r .cib4109 | /bin/bash
          echo $z04 | jq -r .pish811 | /bin/bash
          echo $w04041 | jq -r .zclw48889 | /bin/bash
          echo $daw55470 | jq -r .ta96744 | /bin/bash
          echo $em7804 | jq -r .mbr55 | /bin/bash
          echo $koms4 | jq -r .vt8234 | /bin/bash
          echo $b836 | jq -r .eedig66 | /bin/bash

